cities = [
    "Karachi", "Lahore", "Islamabad", "Rawalpindi", "Faisalabad",
    "Multan", "Peshawar", "Quetta", "Hyderabad", "Sialkot",
    "Gujranwala", "Bahawalpur", "Sukkur", "Larkana", "Mardan",
    "Mingora", "Sheikhupura", "Kasur", "Okara", "Sargodha",
    "Jhang", "Dera Ghazi Khan", "Chiniot", "Kohat", "Abbottabad",
    "New York", "Los Angeles", "Chicago", "Houston", "Miami",
    "San Francisco", "Dallas", "Seattle", "Boston", "Atlanta",
    "Washington D.C.", "Philadelphia", "Phoenix", "Denver", "Detroit",
    "Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa",
    "London", "Manchester", "Birmingham", "Glasgow", "Liverpool",
    "Paris", "Marseille", "Lyon", "Toulouse", "Nice",
    "Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne",
    "Rome", "Milan", "Naples", "Turin", "Palermo",
    "Madrid", "Barcelona", "Valencia", "Seville", "Bilbao",
    "Lisbon", "Porto", "Brussels", "Amsterdam", "Rotterdam",
    "The Hague", "Copenhagen", "Stockholm", "Oslo", "Helsinki",
    "Warsaw", "Krakow", "Gdansk", "Wroclaw", "Poznan",
    "Prague", "Brno", "Budapest", "Bucharest", "Sofia",
    "Athens", "Thessaloniki", "Istanbul", "Ankara", "Izmir",
    "Dubai", "Abu Dhabi", "Sharjah", "Riyadh", "Jeddah",
    "Dammam", "Mecca", "Medina", "Doha", "Kuwait City",
    "Muscat", "Manama", "Beirut", "Amman", "Damascus",
    "Cairo", "Alexandria", "Giza", "Luxor", "Aswan",
    "Cape Town", "Johannesburg", "Durban", "Pretoria", "Nairobi",
    "Mombasa", "Lagos", "Abuja", "Kano", "Accra",
    "Kumasi", "Dakar", "Casablanca", "Rabat", "Marrakech",
    "Algiers", "Tunis", "Tripoli", "Khartoum", "Addis Ababa",
    "Mogadishu", "Kampala", "Dar es Salaam", "Harare", "Lusaka",
    "Tokyo", "Osaka", "Kyoto", "Nagoya", "Sapporo",
    "Yokohama", "Hiroshima", "Fukuoka", "Sendai", "Kobe",
    "Seoul", "Busan", "Incheon", "Daegu", "Daejeon",
    "Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu",
    "Chongqing", "Wuhan", "Nanjing", "Tianjin", "Xi’an",
    "Hong Kong", "Macau", "Taipei", "Kaohsiung", "Bangkok",
    "Chiang Mai", "Phuket", "Hanoi", "Ho Chi Minh City", "Da Nang",
    "Kuala Lumpur", "Penang", "Johor Bahru", "Singapore", "Jakarta",
    "Bali", "Surabaya", "Bandung", "Medan", "Manila",
    "Cebu", "Davao", "Quezon City", "Makati", "Iloilo",
    "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide",
    "Auckland", "Wellington", "Christchurch", "Suva", "Nadi",
    "Mexico City", "Guadalajara", "Monterrey", "Tijuana", "Cancun",
    "Bogota", "Medellin", "Cali", "Cartagena", "Lima",
    "Cusco", "Santiago", "Valparaiso", "Buenos Aires", "Cordoba",
    "Rosario", "Montevideo", "Asuncion", "La Paz", "Santa Cruz",
    "Quito", "Guayaquil", "Caracas", "Maracaibo", "Georgetown",
    "Paramaribo", "Port of Spain", "San Juan", "Havana", "Santo Domingo",
    "Port-au-Prince", "Panama City", "San Jose", "Kingston", "Nassau",
    "Belmopan", "Guatemala City", "Tegucigalpa", "San Salvador", "Managua",
    "Antigua", "Castries", "Bridgetown", "Roseau", "Basseterre",
    "Kingstown", "Port Louis", "Male", "Colombo", "Kandy",
    "Kathmandu", "Thimphu", "Dhaka", "Chittagong", "Sylhet",
    "Malé", "Islamabad", "Gilgit", "Skardu", "Gwadar",
    "Astana", "Almaty", "Tashkent", "Samarkand", "Bishkek",
    "Dushanbe", "Ulaanbaatar", "Yerevan", "Baku", "Tbilisi",
    "Moscow", "St. Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan",
    "Sochi", "Vladivostok", "Irkutsk", "Omsk", "Krasnoyarsk",
    "Helsinki", "Tallinn", "Riga", "Vilnius", "Minsk",
    "Belgrade", "Zagreb", "Sarajevo", "Skopje", "Podgorica",
    "Ljubljana", "Tirana", "Valletta", "Luxembourg City", "Monaco",
    "San Marino", "Andorra la Vella", "Vaduz", "Reykjavik", "Nuuk",
    "Anchorage", "Honolulu", "Fairbanks", "Juneau", "Guam",
    "Pago Pago", "Saipan", "Palikir", "Majuro", "Funafuti",
    "Port Moresby", "Honiara", "Port Vila", "Apia", "Nuku'alofa",
    "Mumbai", "Delhi", "Kolkata", "Chennai", "Pune"
]


